config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :prompts, only: [:index] do
    collection do
      get :search
    end
  end

  root to: 'prompts#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/prompt_queries/has_search.rb
# frozen_string_literal: true

module PromptQueries
  module HasSearch
    extend ActiveSupport::Concern

    SEARCHABLE_COLUMNS = [:query].freeze
    FILTERABLE_COLUMNS = [:query].freeze

    included do
      extend Pagy::Searchkick

      searchkick  searchable: SEARCHABLE_COLUMNS,
                  match: :word_start,
                  filterable: FILTERABLE_COLUMNS
    end
  end
end

app/models/prompt_query.rb
# frozen_string_literal: true

class PromptQuery < ApplicationRecord
  include ::PromptQueries::HasSearch

  validates :query, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pagy::Backend

  add_flash_types :error
end

app/controllers/prompts_controller.rb
# frozen_string_literal: true

class PromptsController < ApplicationController
  NO_SEARCH_PARAM_MESSAGE = 'Search param not passed'

  rescue_from ActionController::ParameterMissing do |exception|
    redirect_to :prompts, alert: NO_SEARCH_PARAM_MESSAGE
  end

  def index
    @pagy, @prompts = pagy PromptQuery.all
  end

  def search
    @pagy, @prompts = pagy_searchkick PromptQuery.pagy_search(search_param)

    render :index
  end

  private

  def search_param
    @search_param ||= params.require(:search_param)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestCgt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/prompts/index.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/boxicons/2.1.0/css/boxicons.min.css" integrity="sha512-pVCM5+SN2+qwj36KonHToF2p1oIvoU3bsqxphdOIWMYmgr4ZqD3t5DjKvvetKhXGc/ZG5REYTT6ltKfExEei/Q==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/5.3.45/css/materialdesignicons.css" integrity="sha256-NAxhqDvtY0l4xn+YVa6WjAcmd94NNfttjNsDmNatFVc=" crossorigin="anonymous" />

<%- flash.each do |_type, msg| %>
  <div class="alert alert-danger" role="alert">
    <%= msg %>
  </div>
<% end %>

<div class="container">
  <div class="row align-items-center">
    <div class="col-md-6">
      <h5 class="card-title">Prompts List:</span></h5>
    </div>
    <div class="col-md-6">
      <%= form_tag(search_prompts_path, method: :get, class: "input-group") do %>
        <%= search_field_tag(:search_param, @search_param, class: "form-control rounded", placeholder: "Search") %>
        <%= button_tag("Search", class: "btn btn-outline-primary") %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="">
        <div class="table-responsive">
          <table class="table project-list-table align-middle table-borderless">
            <thead>
              <tr>
                <th scope="col">Query List:</th>
                <th scope="col" style="width: 100px;">Actions:</th>
              </tr>
            </thead>
            <tbody>
              <%- @prompts.each do |row| %>
                <tr>
                  <td><%= row.query -%></td>
                  <td>
                    <ul class="list-inline mb-0">
                      <li class="list-inline-item">
                        <a href="javascript:void(0);" data-bs-toggle="tooltip" data-bs-placement="top" title="Edit" class="px-2 text-primary">
                          <i class="bx bx-pencil font-size-18"></i>
                        </a>
                      </li>
                      <li class="list-inline-item">
                        <a href="javascript:void(0);" data-bs-toggle="tooltip" data-bs-placement="top" title="Delete" class="px-2 text-danger">
                          <i class="bx bx-trash-alt font-size-18"></i>
                        </a>
                      </li>
                    </ul>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  <div class="row g-0 align-items-center pb-4">
    <div class="col-sm-8">
      <div class="float-sm-end">
        <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
      </div>
    </div>
  </div>
</div>